/**
 * atlas-desc-fr.js — LOT 1 des descriptions pédagogiques FR (clé = nom EN minuscule).
 * Rédaction par lots (un système à la fois) ; les structures sans entrée n'affichent
 * aucun paragraphe (choix UX : pas de remplissage générique). Pensé pour être étendu.
 */
export const DESCRIPTIONS_FR = {
    heart: 'Pompe musculaire du thorax : côté droit vers les poumons, côté gauche vers tout le corps.',
    lung: 'Organe de la respiration : l’oxygène passe dans le sang, le CO2 est rejeté à l’expiration.',
    liver: 'Gros organe sous le diaphragme à droite : nutriments, bile, protéines sanguines.',
    gallbladder: 'Petite poche sous le foie : stocke et concentre la bile qui digère les graisses.',
    kidney: 'Filtre du sang : produit l’urine, équilibre eau, sels et pression artérielle.',
    ureter: 'Fin conduit qui porte l’urine du rein vers la vessie, par ondes de contraction.',
    'urinary bladder': 'Réservoir musculaire pelvien : stocke l’urine venue des reins.',
    stomach: 'Poche musculaire entre œsophage et intestin : stockage, acidité, enzymes.',
    spleen: 'Organe lymphoïde en haut à gauche de l’abdomen : filtre le sang, immunité.',
    pancreas: 'Glande digestive + endocrine : enzymes intestinales, insuline et glucagon.',
    'small intestine': 'Long tube pelotonné : c’est ici qu’a lieu l’essentiel de la digestion et de l’absorption.',
    colon: 'Gros intestin : réabsorbe l’eau et compacte les selles vers le rectum.',
    rectum: 'Dernier segment digestif : stocke les selles avant l’évacuation.',
    appendix: 'Petit diverticule du cæcum : rôle immunitaire débattu, s’enflamme dans l’appendicite.',
    duodenum: 'Premier segment de l’intestin grêle : reçoit bile et suc pancréatique.',
    peritoneum: 'Membrane séreuse qui tapisse l’abdomen et maintient les viscères en place.',
    brain: 'Organe central du système nerveux : perception, mouvement, mémoire, langage.',
    cerebellum: 'Petit cerveau à l’arrière : coordination, équilibre et précision des gestes.',
    'spinal cord': 'Prolonge l’encéphale dans la colonne : relais des ordres moteurs et des sensations.',
    nerve: 'Câble de fibres qui conduit les signaux entre le corps et le système nerveux central.',
    retina: 'Couche du fond de l’œil : capte la lumière et la convertit en signal nerveux.',
    cochlea: 'Organe de l’audition dans l’oreille interne : transforme les vibrations en signal nerveux.',
    eye: 'Organe de la vue : capte la lumière et l’orientation dans l’espace.',
    ear: 'Organe de l’audition et de l’équilibre : oreille externe, moyenne et interne.',
    tongue: 'Muscle du goût et de la parole, premier temps de la déglutition.',
    larynx: 'Organe de la voix entre pharynx et trachée, protège les voies aériennes.',
    pharynx: 'Carrefour gorge : fait passer l’air vers la trachée et les aliments vers l’œsophage.',
    esophagus: 'Tube musculaire qui propulse les aliments vers l’estomac par péristaltisme.',
    trachea: 'Conduit larynx→bronches, maintenu ouvert par ses cartilages.',
    bronchus: 'Branche issue de la trachée qui ventile chaque poumon, jusqu’aux bronchioles.',
    diaphragm: 'Large muscle thorax/abdomen : en se contractant, il fait entrer l’air.',
    pleura: 'Double membrane autour du poumon : glissement sans frottement à la respiration.',
    aorta: 'Plus grosse artère du corps : distribue le sang oxygéné depuis le ventricule gauche.',
    artery: 'Vaisseau à paroi épaisse qui porte le sang du cœur vers les organes.',
    vein: 'Vaisseau qui ramène le sang vers le cœur, aidé par les valvules et les muscles.',
    thyroid: 'Glande du cou en forme de papillon : hormones qui règlent le métabolisme.',
    thymus: 'Organe lymphoïde du thorax, actif chez l’enfant : maturation des lymphocytes T.',
    tonsil: 'Masse lymphoïde de la gorge : première barrière immunitaire, s’enflamme (angine).',
    'adrenal gland': 'Glande au-dessus du rein : adrénaline et cortisol (stress, tension).',
    'pituitary gland': 'Glande chef sous le cerveau : commande les autres glandes endocrines.',
    ovary: 'Gonade féminine : produit ovules et hormones (œstrogènes, progestérone).',
    testis: 'Gonade masculine : produit spermatozoïdes et testostérone.',
    uterus: 'Organe pelvien féminin : accueille la grossesse, se contracte à l’accouchement.',
    prostate: 'Glande masculine sous la vessie : sécrète une partie du sperme, grossit avec l’âge.',
    skin: 'Plus grand organe : barrière, sensation, thermorégulation, vitamine D.',
    bone: 'Tissu vivant minéralisé : soutien, protection, réserve de calcium, moelle sanguine.',
    muscle: 'Faisceau de fibres qui se contracte : mouvement, posture, chaleur.',
    rib: 'Os plat de la cage thoracique : protège cœur et poumons, bouge à la respiration.',
    vertebra: 'Os empilé de la colonne : protège la moelle, porte le tronc avec les disques.',
    skull: 'Boîte crânienne + face : protège l’encéphale et porte les organes des sens.',
    sternum: 'Os médian du thorax où s’articulent côtes et clavicules ; repère du massage cardiaque.',
    femur: 'Os le plus long du corps, cuisse : supporte le poids, fracture grave chez la personne âgée.',
    humerus: 'Os du bras, épaule→coude : s’articule avec omoplate, radius et ulna.',
    pelvis: 'Bassin osseux : transmet le poids vers les jambes, protège les organes pelviens.',
    joint: 'Articulation : zone mobile entre deux os, lubrifiée par le liquide synovial.',
    cartilage: 'Tissu souple et lisse : amortit les articulations et rigidifie nez, oreilles, trachée.',
    ligament: 'Bande fibreuse qui stabilise les articulations en reliant les os.',
    tendon: 'Câble qui transmet la force du muscle à l’os ; s’enflamme (tendinite).',

    // Appareil cardiovasculaire & valves
    valve: 'Dispositif anti-reflux assurant le sens unique de circulation du sang dans les cavités cardiaques.',
    'aortic valve': 'Valve à trois sigmoïdes séparant le ventricule gauche de l\'aorte : s\'ouvre en systole pour éjecter le sang vers tout le corps.',
    'mitral valve': 'Valve atrio-ventriculaire gauche à deux feuillets : empêche le reflux du sang vers l\'oreillette gauche pendant la contraction du ventricule.',
    'tricuspid valve': 'Valve atrio-ventriculaire droite à trois feuillets : guide le flux sanguin de l\'oreillette droite vers le ventricule droit.',
    'pulmonary valve': 'Valve sigmoïde séparant le ventricule droit de l\'artère pulmonaire : s\'ouvre en systole vers la petite circulation.',
    'left ventricle': 'Chambre musculaire principale à haute pression : propulse le sang oxygéné dans l\'aorte et tout le système artériel.',
    'right ventricle': 'Chambre musculaire propulsant le sang désoxygéné vers les poumons à travers l\'artère pulmonaire.',
    'left atrium': 'Cavité recevant le sang oxygéné issu des quatre veines pulmonaires avant son passage dans le ventricule gauche.',
    'right atrium': 'Cavité recevant le sang désoxygéné des veines caves supérieure et inférieure et du sinus coronaire.',
    'interventricular septum': 'Épaisse cloison musculaire séparant les ventricules gauche et droit, essentielle à la synchronisation ventriculaire.'
};
